version: '3.3'
services:
  oap:
    image: apache/skywalking-oap-server:6.2.0
    restart: always
    ports:
      - 11800:11800
      - 12800:12800
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./swconfig:/skywalking/config
  ui:
    image: apache/skywalking-ui:6.2.0
    depends_on:
      - oap
    links:
      - oap
    restart: always
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Shanghai
      - collector.ribbon.listOfServers=oap:12800
