
server:
  port: 9081
spring:
  application:
    name: demo-service
  datasource:
    url: "jdbc:h2:mem:api;DB_CLOSE_ON_EXIT=TRUE;MODE=PostgreSQL"
    username: "sa"
    password:
    driverClassName: "org.h2.Driver"
